#!/usr/bin/env python3
"""
Build script for AnkiAI add-on
Packages add-on thành file .ankiaddon để upload lên AnkiWeb
"""

import os
import sys
import shutil
import zipfile
import json
from pathlib import Path


def get_addon_root():
    """Lấy đường dẫn root của add-on"""
    return Path(__file__).parent / "AnkiAI_ImageAddon"


def get_manifest():
    """Lấy manifest.json"""
    manifest_path = get_addon_root() / "manifest.json"
    with open(manifest_path, 'r', encoding='utf-8') as f:
        return json.load(f)


def generate_structure():
    """Write a deterministic add-on tree so STRUCTURE.txt never goes stale."""
    addon_root = get_addon_root()
    output_path = Path(__file__).parent / "STRUCTURE.txt"
    excluded_names = {"__pycache__", "models", "logs"}

    def walk(directory: Path, prefix: str = "") -> list[str]:
        allowed_user_file = directory == addon_root / "user_files"
        entries = sorted(
            (
                entry
                for entry in directory.iterdir()
                if entry.name not in excluded_names
                and not entry.name.endswith(".pyc")
                and (not allowed_user_file or entry.name == ".gitkeep")
            ),
            key=lambda entry: (not entry.is_dir(), entry.name.lower()),
        )
        lines: list[str] = []
        for index, entry in enumerate(entries):
            last = index == len(entries) - 1
            branch = "└── " if last else "├── "
            lines.append(f"{prefix}{branch}{entry.name}{'/' if entry.is_dir() else ''}")
            if entry.is_dir():
                lines.extend(walk(entry, prefix + ("    " if last else "│   ")))
        return lines

    output_path.write_text(
        "AnkiAI-ImageAddon Project Structure (auto-generated by build.py)\n\n"
        + f"{addon_root.name}/\n"
        + "\n".join(walk(addon_root))
        + "\n",
        encoding="utf-8",
    )
    print(f"🗂️  Updated structure map: {output_path}")


def validate():
    """
    Validate all Python files before building:
    1. AST parse check for syntax errors (catches f-string nesting, %% typos, etc.)
    2. Template string interpolation check for ui_theme.py
    Returns True if all checks pass, False otherwise.
    """
    import ast
    import re

    addon_root = get_addon_root()
    errors = []

    print("🔍 Validating Python source files...")

    # ── 1. AST syntax check for every .py file ──────────────────────────────
    for root, dirs, files in os.walk(addon_root):
        for file in sorted(files):
            if not file.endswith(".py"):
                continue
            path = Path(root) / file
            try:
                source = path.read_text(encoding="utf-8")
                ast.parse(source, filename=str(path))
                rel = path.relative_to(Path(__file__).parent)
                print(f"   ✓ {rel}")
            except SyntaxError as e:
                rel = path.relative_to(Path(__file__).parent)
                errors.append(f"SyntaxError in {rel}: line {e.lineno} — {e.msg}")
                print(f"   ❌ {rel}: line {e.lineno} — {e.msg}")
            except Exception as e:
                rel = path.relative_to(Path(__file__).parent)
                errors.append(f"ParseError in {rel}: {e}")
                print(f"   ❌ {rel}: {e}")

    # ── 2. ui_theme.py: check for stray '%%' in the CSS template ────────────
    ui_theme_path = addon_root / "modules" / "ui_theme.py"
    if ui_theme_path.exists():
        source = ui_theme_path.read_text(encoding="utf-8")
        # Detect the classic typo: 'return template %% t'
        double_pct = re.search(r"return\s+template\s+%%\s+", source)
        if double_pct:
            errors.append(
                "ui_theme.py: Found 'return template %% t' — "
                "should be 'return template % t'. This causes SyntaxError at runtime."
            )
            print("   ❌ ui_theme.py: 'return template %% t' must be 'return template % t'")

    # ── 3. ui_theme.py: dry-run the stylesheet builder ──────────────────────
    try:
        import importlib.util
        spec = importlib.util.spec_from_file_location("ui_theme_check", ui_theme_path)
        mod = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(mod)
        dark_css = mod.build_stylesheet(dark=True)
        light_css = mod.build_stylesheet(dark=False)
        if len(dark_css) < 500 or len(light_css) < 500:
            errors.append("ui_theme.py: build_stylesheet() returned suspiciously short CSS.")
            print("   ❌ ui_theme.py: stylesheet too short — template substitution may have failed.")
        else:
            print(f"   ✓ ui_theme.py: Dark CSS = {len(dark_css)} chars, Light CSS = {len(light_css)} chars")
    except Exception as e:
        errors.append(f"ui_theme.py runtime check failed: {e}")
        print(f"   ❌ ui_theme.py runtime check: {e}")

    # ── Result ───────────────────────────────────────────────────────────────
    if errors:
        print(f"\n❌ VALIDATION FAILED — {len(errors)} error(s):")
        for err in errors:
            print(f"   • {err}")
        return False
    else:
        print("✅ All validation checks passed!\n")
        return True


def build_addon(output_dir=None):
    """
    Build add-on thành .ankiaddon
    
    Args:
        output_dir: Thư mục output (default: current directory)
    """
    # Always validate before packaging
    if not validate():
        print("\n🚫 Build aborted due to validation errors. Fix them first.")
        sys.exit(1)

    generate_structure()

    addon_root = get_addon_root()
    manifest = get_manifest()
    
    if not output_dir:
        output_dir = Path.cwd()
    else:
        output_dir = Path(output_dir)
    
    output_dir.mkdir(exist_ok=True)
    
    # Tên output file
    version = manifest.get("version", "1.0.0")
    output_file = output_dir / f"AnkiAI_ImageAddon-{version}.ankiaddon"
    
    print(f"📦 Building AnkiAI add-on v{version}...")
    print(f"📁 Source: {addon_root}")
    print(f"📤 Output: {output_file}")
    
    # Tạo zip file
    excluded_dirs = {"__pycache__", "models", "logs"}
    excluded_exts = {".pyc", ".pyo", ".pyd", ".sqlite", ".sqlite-wal", ".sqlite-shm"}

    try:
        with zipfile.ZipFile(output_file, 'w', zipfile.ZIP_DEFLATED) as zipf:
            # Add tất cả files từ addon_root
            for root, dirs, files in os.walk(addon_root):
                # Prune excluded dirs in-place
                dirs[:] = [d for d in sorted(dirs) if d not in excluded_dirs]

                rel_dir = Path(root).relative_to(addon_root)
                is_user_files = rel_dir == Path("user_files") or (rel_dir.parts and rel_dir.parts[0] == "user_files")

                for file in sorted(files):
                    if any(file.endswith(ext) for ext in excluded_exts):
                        continue
                    if file.startswith(".DS_Store") or file.endswith(".log"):
                        continue

                    # Inside user_files/, only package .gitkeep (not runtime data/cache)
                    if is_user_files and file != ".gitkeep":
                        continue

                    file_path = Path(root) / file
                    # Anki add-ons: archive path không include folder name
                    arcname = file_path.relative_to(addon_root)

                    print(f"  ✓ Added: {arcname}")
                    zipf.write(file_path, arcname)
        
        print(f"\n✅ Build thành công!")
        print(f"📦 Output file: {output_file}")
        print(f"📊 File size: {output_file.stat().st_size / 1024:.1f} KB")
        print(f"\n📤 Để upload lên AnkiWeb:")
        print(f"   1. Vào https://ankiweb.net/")
        print(f"   2. Add-ons > Upload")
        print(f"   3. Chọn file: {output_file.name}")
        
        return output_file
    
    except Exception as e:
        print(f"\n❌ Build thất bại:")
        print(f"   Error: {e}")
        sys.exit(1)


def install_locally():
    """Cài đặt add-on ở local để test"""
    addon_root = get_addon_root()
    
    # Xác định đường dẫn addons folder
    if sys.platform == "darwin":  # macOS
        addons_path = Path.home() / "Library/Application Support/Anki2/addons21"
    elif sys.platform == "win32":  # Windows
        addons_path = Path.home() / "AppData/Roaming/Anki2/addons21"
    else:  # Linux
        addons_path = Path.home() / ".local/share/Anki2/addons21"
    
    target_path = addons_path / addon_root.name
    
    print(f"🔗 Installing locally for testing...")
    print(f"   From: {addon_root}")
    print(f"   To:   {target_path}")
    
    try:
        # Nếu đã có, backup cái cũ
        if target_path.exists():
            backup_path = target_path.parent / f"{addon_root.name}.backup"
            if backup_path.exists():
                shutil.rmtree(backup_path)
            shutil.move(str(target_path), str(backup_path))
            print(f"   📦 Backed up old version to {backup_path.name}")
        
        # Copy add-on
        shutil.copytree(addon_root, target_path)
        print(f"\n✅ Installed successfully!")
        print(f"🎯 Now open Anki to test")
        
    except Exception as e:
        print(f"\n❌ Installation failed:")
        print(f"   Error: {e}")
        sys.exit(1)


def clean():
    """Xóa __pycache__ và .pyc files"""
    addon_root = get_addon_root()
    
    print("🧹 Cleaning up...")
    
    for root, dirs, files in os.walk(addon_root):
        # Xóa __pycache__
        pycache_dir = Path(root) / '__pycache__'
        if pycache_dir.exists():
            shutil.rmtree(pycache_dir)
            print(f"   ✓ Removed: {pycache_dir}")
        
        # Xóa .pyc
        for file in files:
            if file.endswith('.pyc'):
                file_path = Path(root) / file
                file_path.unlink()
                print(f"   ✓ Removed: {file_path}")
    
    print("✅ Cleanup completed!")


def main():
    """Main entry point"""
    
    if len(sys.argv) < 2:
        print("""
AnkiAI Build Script
====================

Usage:
  python build.py build [output_dir]    - Validate + Build .ankiaddon file
  python build.py validate              - Run validation checks only
  python build.py install               - Install locally for testing
  python build.py clean                 - Clean cache files

Examples:
  python build.py validate              # Check for syntax errors before building
  python build.py build                 # Validate, then create in current directory
  python build.py build ~/Desktop       # Validate, then create in Desktop
  python build.py install               # Install to Anki addons folder
  python build.py clean                 # Remove __pycache__
        """)
        sys.exit(0)
    
    command = sys.argv[1]
    
    if command == "build":
        output_dir = sys.argv[2] if len(sys.argv) > 2 else None
        build_addon(output_dir)
    
    elif command == "validate":
        ok = validate()
        sys.exit(0 if ok else 1)
    
    elif command == "install":
        install_locally()
    
    elif command == "clean":
        clean()
    
    else:
        print(f"❌ Unknown command: {command}")
        sys.exit(1)


if __name__ == "__main__":
    main()
